-- OZZI Real Estate Egypt - Supabase setup
-- Run this entire file in Supabase SQL Editor.
-- Then create your first account from admin.html and run the final INSERT below
-- with that user's Auth UUID.

create extension if not exists pgcrypto;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  purpose text not null check (purpose in ('sale','rent')),
  type text not null,
  title text not null,
  location text not null,
  location_name text not null,
  price numeric(14,2) not null default 0,
  area numeric(12,2),
  rooms integer default 0,
  bathrooms integer default 0,
  garages integer default 0,
  description text,
  features text[] default '{}',
  image_url text,
  status text not null default 'active' check (status in ('active','sold','rented','draft')),
  created_at timestamptz not null default now()
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price numeric(14,2) not null default 0,
  unit text not null default 'قطعة',
  description text,
  image_url text,
  stock numeric(14,2) default 0,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  email text,
  request_type text not null default 'general',
  property_id bigint references public.properties(id) on delete set null,
  material_id bigint references public.materials(id) on delete set null,
  message text,
  status text not null default 'new' check (status in ('new','contacted','closed')),
  created_at timestamptz not null default now()
);

alter table public.admins enable row level security;
alter table public.properties enable row level security;
alter table public.materials enable row level security;
alter table public.inquiries enable row level security;

-- Helper function used by admin-only policies.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins
    where user_id = auth.uid()
  );
$$;

-- Public visitors can see active listings only.
drop policy if exists "public read active properties" on public.properties;
create policy "public read active properties"
on public.properties for select
to anon, authenticated
using (status = 'active' or public.is_admin());

drop policy if exists "admins manage properties" on public.properties;
create policy "admins manage properties"
on public.properties for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public read active materials" on public.materials;
create policy "public read active materials"
on public.materials for select
to anon, authenticated
using (status = 'active' or public.is_admin());

drop policy if exists "admins manage materials" on public.materials;
create policy "admins manage materials"
on public.materials for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public create inquiries" on public.inquiries;
create policy "public create inquiries"
on public.inquiries for insert
to anon, authenticated
with check (true);

drop policy if exists "admins read inquiries" on public.inquiries;
create policy "admins read inquiries"
on public.inquiries for select
to authenticated
using (public.is_admin());

drop policy if exists "admins update inquiries" on public.inquiries;
create policy "admins update inquiries"
on public.inquiries for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins read own admin row" on public.admins;
create policy "admins read own admin row"
on public.admins for select
to authenticated
using (user_id = auth.uid());

-- Storage bucket for listing/product images.
insert into storage.buckets (id, name, public)
values ('ozzi-images', 'ozzi-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read ozzi images" on storage.objects;
create policy "public read ozzi images"
on storage.objects for select
to public
using (bucket_id = 'ozzi-images');

drop policy if exists "admins upload ozzi images" on storage.objects;
create policy "admins upload ozzi images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'ozzi-images' and public.is_admin());

drop policy if exists "admins update ozzi images" on storage.objects;
create policy "admins update ozzi images"
on storage.objects for update
to authenticated
using (bucket_id = 'ozzi-images' and public.is_admin())
with check (bucket_id = 'ozzi-images' and public.is_admin());

drop policy if exists "admins delete ozzi images" on storage.objects;
create policy "admins delete ozzi images"
on storage.objects for delete
to authenticated
using (bucket_id = 'ozzi-images' and public.is_admin());

-- After creating your first account in admin.html:
-- 1) Go to Supabase Dashboard -> Authentication -> Users.
-- 2) Copy that user's UUID.
-- 3) Run:
-- insert into public.admins(user_id) values ('YOUR-AUTH-USER-UUID');
